// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAInOZBCxKN0PDFCVo7uzj7C_SZVRi2Wc',
    appId: '1:686956497714:web:PLACEHOLDER',
    messagingSenderId: '686956497714',
    projectId: 'women-safety-app-e6712',
    authDomain: 'women-safety-app-e6712.firebaseapp.com',
    storageBucket: 'women-safety-app-e6712.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAInOZBCxKN0PDFCVo7uzj7C_SZVRi2Wc',
    appId: '1:686956497714:android:3869c0e4b9d55647b4e52b',
    messagingSenderId: '686956497714',
    projectId: 'women-safety-app-e6712',
    authDomain: 'women-safety-app-e6712.firebaseapp.com',
    storageBucket: 'women-safety-app-e6712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAInOZBCxKN0PDFCVo7uzj7C_SZVRi2Wc',
    appId: '1:686956497714:ios:PLACEHOLDER',
    messagingSenderId: '686956497714',
    projectId: 'women-safety-app-e6712',
    authDomain: 'women-safety-app-e6712.firebaseapp.com',
    storageBucket: 'women-safety-app-e6712.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );
}
